name: maps_sample_app
description: Maps Sample App com geolocalização - Exercício BRADEMO Aula 8
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.3

  geolocator: ^11.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
